### PR TITLE
Corrected temporal subcycling algorithm in the Kessler physics routin…

### LINKED ISSUE #21: Correct algorithm bugs in the Kessler physics routine
The temporal subcycling algorithm in Kessler is broken.
The hardcoded value of `kappa` is incorrect and should be aligned with the standard CESM value.

### PR DESCRIPTION
**Pull request by cjablono**
Corrected temporal subcycling algorithm in the Kessler physics routine
Included the gas constant for dry air
Corrected the constants in the Kessler routine
Fixed formatting and improved documentation.
fixes #21

### CODE REVIEW

**Comment by cjablono** [comment]
Hi Cheryl,
many thanks.
Please feel free to put in extra line breaks into the comment sections (longer than 132 characters).
Best,
Christiane

**Comment by gold2718** [comment]
@cjablono, Since the code is on your branch, the standard procedure is for you to make the necessary fixes, re-test, commit them, and push the commit(s) back to your GitHub. That will automatically update the pull request. 
There is more detail about the PR workflow in step 10 of the [CAM development workflow](https://github.com/ESCOMP/CAM/wiki/CAM-Development-Workflow-in-GitHub) wiki page.

**Comment by brian-eaton** [comment]
I just verified that the files in the fix_kessler branch are identical to the one's in `/glade/u/home/cjablono/CAM/src/atmos_phys/kessler/.`

**Comment by cjablono** [comment]
Hi all,
many thanks for double checking the Kessler changes.
We should be all set with Kessler from my viewpoint. In case you would like me to
test something after the final merge of all the simple physics changes and Kessler
please let me know.
Many thanks,
Christiane

File: kessler/kessler.F90 [hunk 1]
```diff
@@ -14,17 +14,19 @@ module kessler
    real(kind_phys) :: cp    ! heat capacity at constant pressure, J/(kgK)
    real(kind_phys) :: lv    ! latent heat of vaporization, J/kg
    real(kind_phys) :: psl   ! reference pressure at sea level, mb
+   real(kind_phys) :: rair  ! dry air gas constant J/(kgK)
```
Comment (gold2718) [inline kessler/kessler.F90:17]: Instead of `rair`, why not replace it with `inv_kappa` or something similar, calcualte it in `kessler_init` and then use it in `kessler_run` instead of `xk`? You have no other use of `rair`.
